# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Kw < Formula
  desc "Small cli tool for switching between multiple kubeconfigs"
  homepage "https://github.com/Diaphteiros/kw"
  url "https://github.com/Diaphteiros/kw/archive/refs/tags/v1.1.5.tar.gz"
  version "1.1.5"
  sha256 "dd64d4c714e220907f24bd1a9a0773dd5c890d4bc89fb4aa7562732a7b9d138a"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/Diaphteiros/kw/releases/download/v1.1.5/kw-1.1.5-darwin-amd64.tar.gz"
      sha256 "8927adb6bb0221d84a8cd910a8c66800cc29406286054888a6fd69ddad77d8c2"
    end

    on_arm do
      url "https://github.com/Diaphteiros/kw/releases/download/v1.1.5/kw-1.1.5-darwin-arm64.tar.gz"
      sha256 "d29e64a5a53e6654fef55cebc6132edf802b38ecaef7dc2d23f7fc5e5aecbd5f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Diaphteiros/kw/releases/download/v1.1.5/kw-1.1.5-linux-amd64.tar.gz"
      sha256 "1612970a9a05f4a601a403d56a2065af801f0e3583a92f7f3ec4f04f84892e36"
    end

    on_arm do
      url "https://github.com/Diaphteiros/kw/releases/download/v1.1.5/kw-1.1.5-linux-arm64.tar.gz"
      sha256 "c30c67fc98f9b412cd6b978753e2e3b571a09ffa59e5373dddaaa9f05ef942b6"
    end
  end

  def install
    bin.install "kw"
  end
end
