# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class KwGarden < Formula
  desc "Plugin for 'kw' for interacting with a gardener landscape"
  homepage "https://github.com/Diaphteiros/kw_garden"
  url "https://github.com/Diaphteiros/kw_garden/archive/refs/tags/v1.2.2.tar.gz"
  version "1.2.2"
  sha256 "f07113be965cccef1b926861de3c3136de085ef292953b8ae04c69c9ba161fb6"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/Diaphteiros/kw_garden/releases/download/v1.2.2/kw_garden-1.2.2-darwin-amd64.tar.gz"
      sha256 "96f55c3fc9bb9e05069701e3a22614282acbabe0cd0380b3ab346ec088c992db"
    end

    on_arm do
      url "https://github.com/Diaphteiros/kw_garden/releases/download/v1.2.2/kw_garden-1.2.2-darwin-arm64.tar.gz"
      sha256 "ae8d3f7bfa72f7350a663e94e63d2107a1b363b734e637e97b5f88882987da96"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Diaphteiros/kw_garden/releases/download/v1.2.2/kw_garden-1.2.2-linux-amd64.tar.gz"
      sha256 "b77ca2cf254a410d575b1094675606bd52a5a3e40f39175f8ddf8dc405c2e4a0"
    end

    on_arm do
      url "https://github.com/Diaphteiros/kw_garden/releases/download/v1.2.2/kw_garden-1.2.2-linux-arm64.tar.gz"
      sha256 "ec2f3992fd90dd97b8cfa2ce904b568198d6ec3edd33b64c033dc1ce0806f09f"
    end
  end

  def install
    bin.install "kw_garden"
  end
end
