# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class KwGarden < Formula
  desc "Plugin for 'kw' for interacting with a gardener landscape"
  homepage "https://github.com/Diaphteiros/kw_garden"
  url "https://github.com/Diaphteiros/kw_garden/archive/refs/tags/v1.2.1.tar.gz"
  version "1.2.1"
  sha256 "01a1a3ca6d95a3afc7d9d661ad5822c0bfc6c10caadd666e291fafed5eeb27d3"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/Diaphteiros/kw_garden/releases/download/v1.2.1/kw_garden-1.2.1-darwin-amd64.tar.gz"
      sha256 "9034c97a0ae436b5e094b34a84373ced9ac3ac45079bb8e91c8fd9c571d4cb81"
    end

    on_arm do
      url "https://github.com/Diaphteiros/kw_garden/releases/download/v1.2.1/kw_garden-1.2.1-darwin-arm64.tar.gz"
      sha256 "0062359fcd6793670112f0fe5ddf6b04408133c5eb2e37e1ec541bad591c0844"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Diaphteiros/kw_garden/releases/download/v1.2.1/kw_garden-1.2.1-linux-amd64.tar.gz"
      sha256 "7b4649cf93637e7e2a4ea9e1537b94daf30e067e333d57cf51a54df1bef44f90"
    end

    on_arm do
      url "https://github.com/Diaphteiros/kw_garden/releases/download/v1.2.1/kw_garden-1.2.1-linux-arm64.tar.gz"
      sha256 "628126a7f15c6532355776bab473923f3468323f47d464891b5b519e7341a180"
    end
  end

  def install
    bin.install "kw_garden"
  end
end
