# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class KwGarden < Formula
  desc "Plugin for 'kw' for interacting with a gardener landscape"
  homepage "https://github.com/Diaphteiros/kw_garden"
  url "https://github.com/Diaphteiros/kw_garden/archive/refs/tags/v1.2.0.tar.gz"
  sha256 "59f288dd3fc7c2d44a5da752251b0624a8219573131d8b9f9052c09dabfab536"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/Diaphteiros/kw_garden/releases/download/v1.2.0/kw_garden-1.2.0-darwin-amd64.tar.gz"
      sha256 "f7561aa23b6509d7fec4be243e6d97e096e934b8f4dccf1be2215292c0a6d366"
    end

    on_arm do
      url "https://github.com/Diaphteiros/kw_garden/releases/download/v1.2.0/kw_garden-1.2.0-darwin-arm64.tar.gz"
      sha256 "dd0ccddac77b61413d950261479cb5847da9068ebeed6ef20b76cc209c948560"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Diaphteiros/kw_garden/releases/download/v1.2.0/kw_garden-1.2.0-linux-amd64.tar.gz"
      sha256 "ea53e520128dfd9e5e6811ed5db328b73c73f7fd5793afaf5ba6627bad69c6b6"
    end

    on_arm do
      url "https://github.com/Diaphteiros/kw_garden/releases/download/v1.2.0/kw_garden-1.2.0-linux-arm64.tar.gz"
      sha256 "ab7532e8a49ceba31f43b63fda3aec4b7c6bebe6439dd278030e831ba051a1c7"
    end
  end

  def install
    bin.install "kw_garden"
  end
end
