# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class KwKind < Formula
  desc "Kubeswitcher plugin for switching to 'kind' clusters"
  homepage "https://github.com/Diaphteiros/kw_kind"
  url "https://github.com/Diaphteiros/kw_kind/archive/refs/tags/v1.2.0.tar.gz"
  sha256 "ccfb16b5c7741efc276543be98f70ac82db15ac9439c16b38ae27a7def5c81af"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/Diaphteiros/kw_kind/releases/download/v1.2.0/kw_kind-1.2.0-darwin-amd64.tar.gz"
      sha256 "a427e9eed43f44638083def1111f0f4bed992c1cb1903a4c7ff1f9dfc4c5e7cb"
    end

    on_arm do
      url "https://github.com/Diaphteiros/kw_kind/releases/download/v1.2.0/kw_kind-1.2.0-darwin-arm64.tar.gz"
      sha256 "e2a44dd52705561f44cb9632607e391d1ebbf1e93b6288b36bb7eea9e4ef1172"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Diaphteiros/kw_kind/releases/download/v1.2.0/kw_kind-1.2.0-linux-amd64.tar.gz"
      sha256 "e4bf44c6ee17d7dbb5dcf510fa2cb499535369aeda412900950962ac8533b0e6"
    end

    on_arm do
      url "https://github.com/Diaphteiros/kw_kind/releases/download/v1.2.0/kw_kind-1.2.0-linux-arm64.tar.gz"
      sha256 "1b90d89f14a8c040e38c0d190245b027f423cb6dfab2e31572e94757299fa587"
    end
  end

  def install
    bin.install "kw_kind"
  end
end
