# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class KwKind < Formula
  desc "Kubeswitcher plugin for switching to 'kind' clusters"
  homepage "https://github.com/Diaphteiros/kw_kind"
  url "https://github.com/Diaphteiros/kw_kind/archive/refs/tags/v1.2.1.tar.gz"
  version "1.2.1"
  sha256 "1dc79422b281278000c3a652d73a2391de2eeb4b6ff85a2460f4a91302f8613a"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/Diaphteiros/kw_kind/releases/download/v1.2.1/kw_kind-1.2.1-darwin-amd64.tar.gz"
      sha256 "444c26e89bfed8ddd1d526719447fb496808ce811406de053653ce783d89248d"
    end

    on_arm do
      url "https://github.com/Diaphteiros/kw_kind/releases/download/v1.2.1/kw_kind-1.2.1-darwin-arm64.tar.gz"
      sha256 "851a3e8c14d1b35daa1c7e3a688eddd37309ba6bc52e18b4a1ba4a2132015fca"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Diaphteiros/kw_kind/releases/download/v1.2.1/kw_kind-1.2.1-linux-amd64.tar.gz"
      sha256 "97196efe3cf625b7f07a3edac55273517b5c39cddb9ba40e20a78030bbebe306"
    end

    on_arm do
      url "https://github.com/Diaphteiros/kw_kind/releases/download/v1.2.1/kw_kind-1.2.1-linux-arm64.tar.gz"
      sha256 "db3d371c94676b59c37d391d541a34283540e679b9b3f8510621787e558b5c33"
    end
  end

  def install
    bin.install "kw_kind"
  end
end
