# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class KwMcpu < Formula
  desc "Kubeswitcher plugin for switching between the clusters of an openmcp landscape"
  homepage "https://github.com/Diaphteiros/kw_mcpu"
  url "https://github.com/Diaphteiros/kw_mcpu/archive/refs/tags/v0.0.3.tar.gz"
  version "0.0.3"
  sha256 "c66740811659d8b8ce93975ec680e02088d27c093c04d7163662ee12d3051314"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/Diaphteiros/kw_mcpu/releases/download/v0.0.3/kw_mcpu-0.0.3-darwin-amd64.tar.gz"
      sha256 "e64f4b3c5ccb18bc17d12f2bc909b3124f0fc13d9ffc3868aaaf9813d54bd248"
    end

    on_arm do
      url "https://github.com/Diaphteiros/kw_mcpu/releases/download/v0.0.3/kw_mcpu-0.0.3-darwin-arm64.tar.gz"
      sha256 "1c8cee7c41882dae9cfaeae2b472f3cb1f810e6b0801f9eb2e7bbd380756a15a"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Diaphteiros/kw_mcpu/releases/download/v0.0.3/kw_mcpu-0.0.3-linux-amd64.tar.gz"
      sha256 "fdd618174919505badb54f824dbebae2f8094921dfae5eeee8e87febb72c846f"
    end

    on_arm do
      url "https://github.com/Diaphteiros/kw_mcpu/releases/download/v0.0.3/kw_mcpu-0.0.3-linux-arm64.tar.gz"
      sha256 "3fbc988a55f83662a82a3764d9d1870fe4fbde4ec32627f6a3cdfe3b86eb7e70"
    end
  end

  def install
    bin.install "kw_mcpu"
  end
end
