# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class KwMcp < Formula
  desc "Kubeswitcher plugin for the openmcp project"
  homepage "https://github.com/Diaphteiros/kw_mcp"
  url "https://github.com/Diaphteiros/kw_mcp/archive/refs/tags/v0.0.2.tar.gz"
  sha256 "768938941c8ad59715617bb056e566a4586bc37464f8f4226f6421dc27c6993c"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/Diaphteiros/kw_mcp/releases/download/v0.0.2/kw_mcp-0.0.2-darwin-amd64.tar.gz"
      sha256 "997fe2d18ab6b0ed18ffa7e3c65861f4e3a5f084ba3abc466f8622d7a0d7ea73"
    end

    on_arm do
      url "https://github.com/Diaphteiros/kw_mcp/releases/download/v0.0.2/kw_mcp-0.0.2-darwin-arm64.tar.gz"
      sha256 "23f8f3700f133ac1e1f203da3735f7c18df4b22c6484a54b0ca44a5b6bd036f4"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Diaphteiros/kw_mcp/releases/download/v0.0.2/kw_mcp-0.0.2-linux-amd64.tar.gz"
      sha256 "83d7678fe3567a6d8e3423504999cf1d59ad3228a01fbc9a3d687bf32d5d0fb1"
    end

    on_arm do
      url "https://github.com/Diaphteiros/kw_mcp/releases/download/v0.0.2/kw_mcp-0.0.2-linux-arm64.tar.gz"
      sha256 "649dccaafbf398d1b062550a758cadfd1bf2aa687fc620b6f3d5126801292e92"
    end
  end

  def install
    bin.install "kw_mcp"
  end
end
