# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class KwMcpu < Formula
  desc "Kubeswitcher plugin for switching between the clusters of an openmcp landscape"
  homepage "https://github.com/Diaphteiros/kw_mcpu"
  url "https://github.com/Diaphteiros/kw_mcpu/archive/refs/tags/v0.0.1.tar.gz"
  sha256 "ead5a4345d2fdb4f675a60db6f8dda6bae4d4b842498775f1a393ad2bfe0b058"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/Diaphteiros/kw_mcpu/releases/download/v0.0.1/kw_mcpu-0.0.1-darwin-amd64.tar.gz"
      sha256 "106be25d9709b3aa4a5b891c84b0614c248e09efe9c69d67a1ac2c5b4faed61d"
    end

    on_arm do
      url "https://github.com/Diaphteiros/kw_mcpu/releases/download/v0.0.1/kw_mcpu-0.0.1-darwin-arm64.tar.gz"
      sha256 "54ac444dffe10bdb2a896f061aeae51722d17d47da44501e779dad0571927221"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Diaphteiros/kw_mcpu/releases/download/v0.0.1/kw_mcpu-0.0.1-linux-amd64.tar.gz"
      sha256 "b05b83857d16b394bcb21f7573f01865eaf407720aeb1e8371f3658f101d0c29"
    end

    on_arm do
      url "https://github.com/Diaphteiros/kw_mcpu/releases/download/v0.0.1/kw_mcpu-0.0.1-linux-arm64.tar.gz"
      sha256 "6d2a5b5dcd623d1c335427752be4c4ce3b5ba413a31062dced535e288b0c3277"
    end
  end

  def install
    bin.install "kw_mcpu"
  end
end
